AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyLambdaFunction1:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function1.lambda_handler
      Runtime: python3.12
      Code:
        S3Bucket: sahil-bucket-cf-1
        S3Key: lambda_function1.zip
      Timeout: 60
      Role: !GetAtt LambdaFunction1Role.Arn

  LambdaFunction1Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"