name: Snyk Scan and Deploy 2

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag to deploy'
        required: true
        default: 'v1.0.0'
      stack_name:
        description: 'Name of the CloudFormation stack'
        required: true
        default: 'MyStack'
      param1:
        description: 'Value for Parameter1'
        required: true
      param2:
        description: 'Value for Parameter2'
        required: true

jobs:
  snyk-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_tag }}

      - name: Set up Node (required for Snyk CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=src/requirements.txt --package-manager=pip --severity-threshold=high

      - name: Run Snyk IAC scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk iac test template.yaml --severity-threshold=high

      - name: Deploy to AWS
        if: success()   # only runs if Snyk passes
        run: |
          echo "Deploying to AWS CloudFormation..."
          # aws cloudformation deploy \
          #   --stack-name ${{ github.event.inputs.stack_name }} \
          #   --template-file template.yaml \
          #   --parameter-overrides \
          #     Parameter1=${{ github.event.inputs.param1 }} \
          #     Parameter2=${{ github.event.inputs.param2 }} \
          #   --capabilities CAPABILITY_NAMED_IAM
